"""Unlisted share pages for depot sessions (the Show HN payload).

One session -> one static HTML page at an unguessable token URL, served
locally at ``/share/{token}``. Sharing is opt-in per session and revocable
(``unshare`` deletes the file). Anyone on your LAN/Tailscale with the link
can read the page - the webapp says so next to the button.

Storage is ``~/.local/share/opencode-cli-mcp/shares/`` (``{token}.html`` plus
``index.json``), overridable via ``OPENCODE_CLI_MCP_SHARES_DIR``. This module
only READS ``opencode.db`` (via :mod:`opencode_cli_mcp.depot`); it never
writes there, per the depot safety model.
"""

import html
import json
import os
import re
import secrets
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from opencode_cli_mcp import depot

SHARES_DIR_ENV = "OPENCODE_CLI_MCP_SHARES_DIR"
TOKEN_BYTES = 16
_TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]{8,128}$")


class ShareError(Exception):
    """Raised when a share cannot be created, read, or removed."""


def shares_dir() -> Path:
    """Share storage dir. Env override wins (tests use it)."""
    env = os.environ.get(SHARES_DIR_ENV)
    if env:
        return Path(env)
    return Path.home() / ".local" / "share" / "opencode-cli-mcp" / "shares"


def _index_path(base: Path) -> Path:
    return base / "index.json"


def _read_index(base: Path) -> dict[str, Any]:
    try:
        data = json.loads(_index_path(base).read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}
    return data if isinstance(data, dict) else {}


def _write_index(base: Path, index: dict[str, Any]) -> None:
    base.mkdir(parents=True, exist_ok=True)
    tmp = base / "index.json.tmp"
    tmp.write_text(json.dumps(index, indent=2), encoding="utf-8")
    tmp.replace(_index_path(base))


def _fmt_ts(ts_ms: Any) -> str:
    try:
        ms = int(ts_ms)
    except (TypeError, ValueError):
        return str(ts_ms) if ts_ms else ""
    try:
        return datetime.fromtimestamp(ms / 1000, tz=UTC).strftime("%Y-%m-%d %H:%M UTC")
    except (OverflowError, OSError, ValueError):
        return str(ts_ms)


def _render_html(title: str, created: str, session_id: str, transcript: list[dict[str, Any]]) -> str:
    rows = []
    for msg in transcript:
        role = html.escape(str(msg.get("role", "unknown")))
        text = html.escape(str(msg.get("text", "")))
        ts = html.escape(_fmt_ts(msg.get("ts")))
        body = f"<pre>{text}</pre>" if "\n" in text else f"<p>{text}</p>"
        rows.append(f"<div class='msg {role}'><p class='ts'>{role} &mdash; {ts}</p>{body}</div>")
    messages = "\n".join(rows) if rows else "<p class='ts'>No text parts in this session.</p>"
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>
body{{max-width:800px;margin:2em auto;padding:0 1em;font:14px/1.6 system-ui;color:#e2e8f0;background:#0f172a}}
h1{{color:#f59e0b;font-size:20px}}
.banner{{border:1px solid #b45309;background:#451a03;border-radius:8px;padding:.75em 1em;margin:1em 0;font-size:13px;color:#fcd34d}}
.msg{{margin:1em 0;padding:1em;border-radius:8px;background:#1e293b}}
.msg.user{{border-left:3px solid #38bdf8}}
.msg.assistant{{border-left:3px solid #f59e0b}}
.ts{{color:#64748b;font-size:12px;margin:0 0 .5em}}
pre{{background:#020617;padding:1em;border-radius:4px;overflow-x:auto;white-space:pre-wrap}}
code{{font:13px/1.5 monospace}}
a{{color:#f59e0b}}
</style></head><body>
<h1>{html.escape(title)}</h1>
<div class="banner">Unlisted share of opencode session <code>{html.escape(session_id)}</code>
 ({html.escape(created)}). Anyone with this link can read it. Generated by opencode-cli-mcp session depot.</div>
{messages}
</body></html>"""


def create_share(
    session_id: str,
    *,
    db_path: Path | None = None,
    base: Path | None = None,
    limit: int = 500,
) -> dict[str, Any]:
    """Render a session as a share page. Returns token + url path + metadata."""
    session = depot.get_session(session_id, db_path=db_path)
    if session is None:
        raise ShareError(f"session not found: {session_id}")
    transcript = depot.get_session_transcript(session_id, limit=limit, db_path=db_path)
    base = base or shares_dir()
    base.mkdir(parents=True, exist_ok=True)
    token = secrets.token_urlsafe(TOKEN_BYTES)
    title = str(session.get("title") or session_id)
    page = _render_html(title, str(session.get("time_created_display") or ""), session_id, transcript)
    (base / f"{token}.html").write_text(page, encoding="utf-8")
    index = _read_index(base)
    index[token] = {
        "session_id": session_id,
        "title": title,
        "created_ms": int(datetime.now(UTC).timestamp() * 1000),
        "messages": len(transcript),
    }
    _write_index(base, index)
    return {
        "token": token,
        "url_path": f"/share/{token}",
        "session_id": session_id,
        "title": title,
        "messages": len(transcript),
    }


def unshare_session(session_id: str, *, base: Path | None = None) -> int:
    """Remove all share pages for a session. Returns pages removed."""
    base = base or shares_dir()
    index = _read_index(base)
    doomed = [t for t, e in index.items() if isinstance(e, dict) and e.get("session_id") == session_id]
    for token in doomed:
        try:
            (base / f"{token}.html").unlink(missing_ok=True)
        except OSError:
            pass
        del index[token]
    if doomed:
        _write_index(base, index)
    return len(doomed)


def unshare_token(token: str, *, base: Path | None = None) -> bool:
    """Remove one share page by token. Returns True if one existed."""
    base = base or shares_dir()
    index = _read_index(base)
    if token not in index:
        return False
    try:
        (base / f"{token}.html").unlink(missing_ok=True)
    except OSError:
        pass
    del index[token]
    _write_index(base, index)
    return True


def list_shares(*, base: Path | None = None) -> list[dict[str, Any]]:
    """All share pages, newest first."""
    base = base or shares_dir()
    index = _read_index(base)
    out = [{"token": t, **e} for t, e in index.items() if isinstance(e, dict)]
    out.sort(key=lambda e: e.get("created_ms", 0), reverse=True)
    return out


def session_share(session_id: str, *, base: Path | None = None) -> dict[str, Any] | None:
    """Newest share page for a session, or None."""
    matches = [s for s in list_shares(base=base) if s.get("session_id") == session_id]
    return matches[0] if matches else None


def share_page_path(token: str, *, base: Path | None = None) -> Path | None:
    """Filesystem path of a share page, or None (unknown/malformed token)."""
    if not token or not _TOKEN_RE.match(token):
        return None
    base = base or shares_dir()
    index = _read_index(base)
    if token not in index:
        return None
    page = base / f"{token}.html"
    return page if page.exists() else None
